### ISSUE TITLE
Reusable chunks missing 

### ISSUE THREAD

**Issue by chrisandrews7** [AppImageCrafters/zsync#2]
# Problem
When calling [SearchReusableChunks](https://github.com/AppImageCrafters/libzsync-go/blob/master/zsync.go#L116) some chunks that have already been downloaded are not returned by this method.

So after downloading a file once and then calling  [Sync](https://github.com/AppImageCrafters/libzsync-go/blob/master/zsync.go#L71) or [GetMissingChunks](https://github.com/AppImageCrafters/libzsync-go/blob/master/zsync.go#L93) a second time. It will always show missing chunks despite the chunks having already been downloaded.

# Possible cause
From what I understand this is caused by the [distribution of work](https://github.com/AppImageCrafters/libzsync-go/blob/master/zsync.go#L139) missing some chunks out.
This occurs when the [division of chunks to workers](https://github.com/AppImageCrafters/libzsync-go/blob/master/zsync.go#L132) has a remainder. 

# Example:
File:
```
001122334455667788
````
Zsync:
```
zsync: 0.6.2
Filename: test.txt
MTime: Tue, 15 Mar 2022 15:29:04 +0000
Blocksize: 2
Length: 18
Hash-Lengths: 2,2,3
URL: test.txt
SHA-1: b359128be3e76a423fb91f1ab7ff86f0a45b0eeb

...
```
Run [SearchReusableChunks](https://github.com/AppImageCrafters/libzsync-go/blob/master/zsync.go#L116) after having the full file contents already present.  

If I have 8 workers, each will take 2 chunks each, leaving 2 which no worker will pick up. Which causes those chunks to be re-downloaded again despite them already existing.

**Comment by chrisandrews7** [comment]
@azubieta

**Comment by azubieta** [comment]
@chrisandrews7 good finding, right now I'm involved on a fix to AppRun which could take me a few weeks more.

Please feel free to send a PR with the changes :)

**Comment by chrisandrews7** [comment]
@azubieta Sure, see https://github.com/AppImageCrafters/libzsync-go/pull/3
